import 'package:flutter/material.dart';

List<IconData> iconsList = [
    Icons.account_balance_wallet,
    Icons.credit_card,
    Icons.album,
    Icons.beach_access,
    Icons.brush,
    Icons.build,
    Icons.cake,
    Icons.business_center,
    Icons.child_friendly,
    Icons.chrome_reader_mode,
    Icons.class_ ,
    Icons.cloud,
    Icons.color_lens,
    Icons.directions_bike,
    Icons.directions_bus,
    Icons.directions_boat,
    Icons.directions_car,
    Icons.directions_railway,
    Icons.domain,
    Icons.email,
    Icons.euro_symbol,
    Icons.ev_station,
    Icons.fastfood,
    Icons.fitness_center,
    Icons.flight,
    Icons.free_breakfast,
    Icons.gavel,
    Icons.hotel,
    Icons.account_balance,
    Icons.home,
    Icons.monetization_on,
    Icons.work,
  ];